#!/usr/bin/env bash
set -euo pipefail

# Run HumanEgo one-step-at-a-time using URDF IK + SDK ABS_JOINT trajectory.
# This bypasses SDK DELTA_POSE/ABS_POSE end-effector control and sends joint
# trajectories interpolated from current q to IK target q. Gripper is disabled
# by default so EE tracking can be evaluated cleanly.

cd "$(dirname "$0")/.."

export G1_HUMANEGO_TAG="${G1_HUMANEGO_TAG:-ik_abs_joint_raw_full_no_gripper}"
export G1_HUMANEGO_CONTROL_MODE="${G1_HUMANEGO_CONTROL_MODE:-prompt}"
export G1_HUMANEGO_CONFIRM="${G1_HUMANEGO_CONFIRM:-RUN_CONTROL}"
export G1_HUMANEGO_MAX_STEPS="${G1_HUMANEGO_MAX_STEPS:-10}"
export G1_HUMANEGO_SEND_DEPTH="${G1_HUMANEGO_SEND_DEPTH:-true}"
export G1_HUMANEGO_OBJECT_LOCK="${G1_HUMANEGO_OBJECT_LOCK:-base_after_first}"
export G1_HUMANEGO_OBJECT_LOCK_REQUIRE_CLEAN="${G1_HUMANEGO_OBJECT_LOCK_REQUIRE_CLEAN:-true}"
export G1_HUMANEGO_TARGET_SOURCE="${G1_HUMANEGO_TARGET_SOURCE:-raw}"
export G1_HUMANEGO_TARGET_ADAPTER="${G1_HUMANEGO_TARGET_ADAPTER:-full}"
export G1_HUMANEGO_TARGET_Z_BIAS_M="${G1_HUMANEGO_TARGET_Z_BIAS_M:-0.0}"
export G1_HUMANEGO_EE_CONTROL_MODE="ik_abs_joint"
export G1_HUMANEGO_CLOSED_LOOP_EE="${G1_HUMANEGO_CLOSED_LOOP_EE:-false}"
export G1_HUMANEGO_IK_ABS_JOINT_WAIST_HEIGHT_OFFSET_M="${G1_HUMANEGO_IK_ABS_JOINT_WAIST_HEIGHT_OFFSET_M:--0.300}"
export G1_HUMANEGO_IK_ABS_JOINT_ARM_STATE_MAPPING="${G1_HUMANEGO_IK_ABS_JOINT_ARM_STATE_MAPPING:-left_first}"
export G1_HUMANEGO_IK_ABS_JOINT_NUM_POINTS="${G1_HUMANEGO_IK_ABS_JOINT_NUM_POINTS:-20}"
export G1_HUMANEGO_IK_ABS_JOINT_REFERENCE_TIME="${G1_HUMANEGO_IK_ABS_JOINT_REFERENCE_TIME:-1.0}"
export G1_HUMANEGO_IK_ABS_JOINT_MAX_DELTA_RAD="${G1_HUMANEGO_IK_ABS_JOINT_MAX_DELTA_RAD:-0.50}"
export G1_HUMANEGO_IK_ABS_JOINT_MAX_NFEV="${G1_HUMANEGO_IK_ABS_JOINT_MAX_NFEV:-300}"
export G1_HUMANEGO_EXECUTE_GRIPPER="${G1_HUMANEGO_EXECUTE_GRIPPER:-false}"
export G1_HUMANEGO_EXECUTE_S="${G1_HUMANEGO_EXECUTE_S:-1.0}"
export G1_HUMANEGO_SETTLE_S="${G1_HUMANEGO_SETTLE_S:-0.5}"
export G1_HUMANEGO_APPROACH_OBJECT_KEY="${G1_HUMANEGO_APPROACH_OBJECT_KEY:-obj1}"

bash scripts/run_g1_humanego_interactive_step_to_public_server.sh "$@"
