#!/usr/bin/env bash
set -euo pipefail

# Run HumanEgo with model inference at each step, then locally close the loop on
# the selected EE target using residual DELTA_POSE commands. Position-only is the
# default diagnostic mode so translation tracking can be isolated from rotation.

cd "$(dirname "$0")/.."

export G1_HUMANEGO_TAG="${G1_HUMANEGO_TAG:-delta_pose_position_closed_loop_no_gripper}"
export G1_HUMANEGO_CONTROL_MODE="${G1_HUMANEGO_CONTROL_MODE:-prompt}"
export G1_HUMANEGO_CONFIRM="${G1_HUMANEGO_CONFIRM:-RUN_CONTROL}"
export G1_HUMANEGO_MAX_STEPS="${G1_HUMANEGO_MAX_STEPS:-1}"
export G1_HUMANEGO_SEND_DEPTH="${G1_HUMANEGO_SEND_DEPTH:-true}"
export G1_HUMANEGO_OBJECT_LOCK="${G1_HUMANEGO_OBJECT_LOCK:-base_after_first}"
export G1_HUMANEGO_OBJECT_LOCK_REQUIRE_CLEAN="${G1_HUMANEGO_OBJECT_LOCK_REQUIRE_CLEAN:-true}"
export G1_HUMANEGO_TARGET_SOURCE="${G1_HUMANEGO_TARGET_SOURCE:-raw}"
export G1_HUMANEGO_TARGET_ADAPTER="${G1_HUMANEGO_TARGET_ADAPTER:-position_only}"
export G1_HUMANEGO_TARGET_Z_BIAS_M="${G1_HUMANEGO_TARGET_Z_BIAS_M:-0.0}"
export G1_HUMANEGO_EE_CONTROL_MODE="${G1_HUMANEGO_EE_CONTROL_MODE:-delta_pose}"
export G1_HUMANEGO_DELTA_POSE_ROTATION_FRAME="${G1_HUMANEGO_DELTA_POSE_ROTATION_FRAME:-base}"
export G1_HUMANEGO_DELTA_POSE_REFERENCE_TIME="${G1_HUMANEGO_DELTA_POSE_REFERENCE_TIME:-0.25}"
export G1_HUMANEGO_EXECUTE_GRIPPER="${G1_HUMANEGO_EXECUTE_GRIPPER:-false}"
export G1_HUMANEGO_EXECUTE_S="${G1_HUMANEGO_EXECUTE_S:-0.25}"
export G1_HUMANEGO_SETTLE_S="${G1_HUMANEGO_SETTLE_S:-0.2}"
export G1_HUMANEGO_CLOSED_LOOP_EE="${G1_HUMANEGO_CLOSED_LOOP_EE:-true}"
export G1_HUMANEGO_CLOSED_LOOP_MAX_ATTEMPTS="${G1_HUMANEGO_CLOSED_LOOP_MAX_ATTEMPTS:-8}"
export G1_HUMANEGO_CLOSED_LOOP_POSITION_TOLERANCE_M="${G1_HUMANEGO_CLOSED_LOOP_POSITION_TOLERANCE_M:-0.01}"
export G1_HUMANEGO_CLOSED_LOOP_ROTATION_TOLERANCE_DEG="${G1_HUMANEGO_CLOSED_LOOP_ROTATION_TOLERANCE_DEG:--1.0}"
export G1_HUMANEGO_CLOSED_LOOP_EXECUTE_S="${G1_HUMANEGO_CLOSED_LOOP_EXECUTE_S:-0.25}"
export G1_HUMANEGO_CLOSED_LOOP_SETTLE_S="${G1_HUMANEGO_CLOSED_LOOP_SETTLE_S:-0.05}"
export G1_HUMANEGO_CLOSED_LOOP_MIN_RESIDUAL_M="${G1_HUMANEGO_CLOSED_LOOP_MIN_RESIDUAL_M:-0.002}"
export G1_HUMANEGO_CLOSED_LOOP_ORIENTATION_MODE="${G1_HUMANEGO_CLOSED_LOOP_ORIENTATION_MODE:-current}"
export G1_HUMANEGO_CLOSED_LOOP_STOP_ON_REGRESS="${G1_HUMANEGO_CLOSED_LOOP_STOP_ON_REGRESS:-true}"
export G1_HUMANEGO_CLOSED_LOOP_REGRESS_PATIENCE="${G1_HUMANEGO_CLOSED_LOOP_REGRESS_PATIENCE:-2}"
export G1_HUMANEGO_APPROACH_OBJECT_KEY="${G1_HUMANEGO_APPROACH_OBJECT_KEY:-obj1}"

bash scripts/run_g1_humanego_interactive_step_to_public_server.sh "$@"
